### ISSUE TITLE
Error mostrado en campos cantidad de Rubros incorrectos

### ISSUE THREAD

**Issue by espidav** [fatimaTalavera/OnProject#114]
Al querer guardar materiales o servicios con cantidades negativas muestra un error de "ingrese un numero menor de 9999",es incorrecto el error mostrado, mostrar el error informando que no esta permitido cantidades negativas o no permitir en el mismo campo numeros negativos para controlar este bug
![4](https://cloud.githubusercontent.com/assets/11951394/24880682/505a0572-1e09-11e7-9718-40a65c39310d.png)

**Comment by alexjw** [comment]
Demasiado pelotudo ya tiene que ser el usuario, voy a preguntarle al profe que dice
