### ISSUE TITLE
No inicia sesion los usuarios creados

### ISSUE THREAD

**Issue by espidav** [fatimaTalavera/OnProject#133]
No se puede iniciar sesion con el usuario creado..luego de ingresar el usuario y la contraseña correcta el sistema muestra un mensaje y no inicia sesion
![captura de pantalla de 2017-04-15 10-40-19](https://cloud.githubusercontent.com/assets/11951394/25064482/e27c46b4-21c8-11e7-88a2-06a77248784a.png)
![captura de pantalla de 2017-04-15 10-42-16](https://cloud.githubusercontent.com/assets/11951394/25064481/dff79e5c-21c8-11e7-994a-289fe75e77f8.png)

**Comment by rsjavier14** [comment]
no es un bug.. cuenta no verificada dice, tenes que usar un correo real, ahi te va a llegar un email con un link para confirmar la cuenta.

**Comment by espidav** [comment]
Al apretar el link de confirmacion de la cuenta  muestra una pagina con error,luego al tratar de iniciar con el correo  vuelve a pedir confirmacion
![captura de pantalla de 2017-04-16 13-27-15](https://cloud.githubusercontent.com/assets/11951394/25072928/c6167ffe-22a8-11e7-8887-cbc33ff5120f.png)
![captura de pantalla de 2017-04-16 13-27-22](https://cloud.githubusercontent.com/assets/11951394/25072929/c6e8fdd0-22a8-11e7-963c-ce6bfc703663.png)
![captura de pantalla de 2017-04-16 13-27-33](https://cloud.githubusercontent.com/assets/11951394/25072930/c875d696-22a8-11e7-8bde-bc7224baa6c7.png)
