### ISSUE TITLE
Campos sin limites en Certificacion interna

### ISSUE THREAD

**Issue by espidav** [fatimaTalavera/OnProject#142]
los campos dias trabajos,jornal, descuento,observacion estan sin limites de caracteres ![captura de pantalla de 2017-04-17 00-44-19](https://cloud.githubusercontent.com/assets/11951394/25079064/13962140-2307-11e7-8aae-36f1e165543c.png)

**Comment by taniamonges** [comment]
si tiene limites, solo que las validaciones que hacemos es en el modelado, al darle click en guardar no te va a dejar si superaste el limite permitido.
