### ISSUE TITLE
Facturar al cliente

### ISSUE THREAD

**Issue by Jorge199** [fatimaTalavera/OnProject#154]

**Comment by taniamonges** [comment]
No funciona
Datos ingresados
![untitled2](https://cloud.githubusercontent.com/assets/11179944/26480937/91d3da3a-41ab-11e7-87af-7bc2df4d2525.png)
Resultado obtenido
![untitled](https://cloud.githubusercontent.com/assets/11179944/26480943/a0614308-41ab-11e7-9d1a-a68f09f00537.png)

**Comment by alexjw** [comment]
Error en producción, seguro hay que hacer drop y migrate de nuevo

**Comment by taniamonges** [comment]
sigue teniendo el mismo error
