### ISSUE TITLE
Incluir numero de revision en la version de la aplicacion de forma automatica

### ISSUE THREAD

**Issue by rsjavier14** [fatimaTalavera/OnProject#159]
Fue sugerido por la profesora, incluir el id del ultimo commit luego de la version quedando de esta forma: **v.0.3.0-nro_revision**

**Comment by rsjavier14** [comment]
Esta tarea ya termine la semana pasada. @Jorge199

**Comment by taniamonges** [comment]
No muestra el número de revisión y deberia ser de la forma  v.0.3.0-nro_revision
Agregar acento a versión
![untitled2](https://cloud.githubusercontent.com/assets/11179944/25930105/45644da4-35d2-11e7-83ad-6249621e23e5.png)
