### ISSUE TITLE
Corregir los errores de roles

### ISSUE THREAD

**Issue by rsjavier14** [fatimaTalavera/OnProject#160]
Errores que surgieron durante la presentacion del ultimo sprint

**Comment by rsjavier14** [comment]
Esta tarea ya termine la semana pasada. @Jorge199

**Comment by taniamonges** [comment]
Tiene error la hora de creacion es incorrecta
Pasos:
1. Crear rol
![untitled](https://cloud.githubusercontent.com/assets/11179944/25955874/5c492e3e-3638-11e7-8874-5161b9ed290a.png)
