### ISSUE TITLE
Realizar nuevas modificaciones a presupuesto 

### ISSUE THREAD

**Issue by EmilioCenturion** [fatimaTalavera/OnProject#161]
Agregar modificaciones dichas por la profesora, agregar campos faltantes para nuevos rubros, agregar otros estados al presupuesto. Otra sugerencia de la profe fue exportar el presupuesto a excel 
Agregar el botón generar contrato desde show de presupuesto

**Comment by taniamonges** [comment]
@EmilioCenturion  exportar presupuesto a excel no hay, debe haber una opcion exportar o no?

**Comment by EmilioCenturion** [comment]
Fue una sugerencia de la profe como mejora nada mas, pero al tratar de implementarlo tuve problemas, pero como no es de prioridad alta deje así nomas
