### ISSUE TITLE
Mejorar show de log de auditoria

### ISSUE THREAD

**Issue by Jorge199** [fatimaTalavera/OnProject#169]
ordenar el listado de registros por su fecha de creación (los mas recientes van primero)
agregar buscador
los nombres de los modelos del listado ,las acciones y los cambios tienen que estar en español

**Comment by alexjw** [comment]
No, en que te fundamentándose para decir que tienen que estar en español los nombre de los MODELOS y las ACCIONES, para confundir?

**Comment by alexjw** [comment]
*En que te fundamentás quise decir

**Comment by Jorge199** [comment]
y en la vista del log no va a ver un programador

**Comment by Jorge199** [comment]
esos dos me parecen mas necesarios poner en español y facilita para entender, igual como para crear los roles, lo cambios no se podríamos dejar nomas así

**Comment by alexjw** [comment]
Cambié el orden y puse el nombre del usuario, hasta ahí nomás, mañana le preguntamos a la profe Mirta

**Comment by taniamonges** [comment]
Cambiar textos en vez de Certificación que diga Certificación Interna, falta acento a certificación.
También falta log de usuario y no tiene filtro o buscador
Ver imagen 
![untitled](https://cloud.githubusercontent.com/assets/11179944/25927381/b1e58628-35c3-11e7-8924-be3cf7673dcc.png)

**Comment by taniamonges** [comment]
@alexjw  no tiene filtro, no se puede hacer busqueda
