### ISSUE TITLE
Formato fecha en factura de compra

### ISSUE THREAD

**Issue by taniamonges** [fatimaTalavera/OnProject#189]
Cuando creas una factura de compra y seleccionas una fecha que no sea la actual aparece en un formato incorrecto.
Ej: 
1.	Click en panel lateral opción factura de compra.
2.	Click en crear factura de compra y rellenar los datos
2.1	Seleccionar fecha: 4 de mayo
2.2	Seleccionar proveedor: inpaco
2.3	Condición: contado
2.4	Número de boleta: 12
2.5	Seleccionar material: cemento
2.6	Click en guardar
3.	Click en editar
![error](https://cloud.githubusercontent.com/assets/11179944/25768946/28db3a0c-31dc-11e7-8e18-868ae0e41d73.png)
![error](https://cloud.githubusercontent.com/assets/11179944/25768956/7c575c60-31dc-11e7-9240-3ff998eb719c.png)

**Comment by fatimaTalavera** [comment]
Agregue fecha actual por defecto
