### ISSUE TITLE
Autenticación de usuario

### ISSUE THREAD

**Issue by fatimaTalavera** [fatimaTalavera/OnProject#2]
Se desea crear un login básico, una pagina para crear y editar usuarios, y una opción para que el usuario pueda cambiar sus propios datos.
Para ello puede valerse de herramientas como devise

**Comment by rsjavier14** [comment]
@ergo-program este issue ya esta completo? si es asi por favor cerrar el issue y moverlo en **Done** en [Project](https://github.com/fatimaTalavera/OnProject/projects/1)

**Comment by ergo-program** [comment]
Si, lo único que falta es cambiar el idioma y listo. Cuando termine eso cierro el issue @rsjavier14
