### ISSUE TITLE
Rubro - validación, mostrar información

### ISSUE THREAD

**Issue by taniamonges** [fatimaTalavera/OnProject#212]
Datos ingresados
1.	Nombre:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
2.	Utilidad: 9999
3.	Unidad de medida: mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
Arreglar:
1. Que unidad de medida muestre en una sola linea
![untitled](https://cloud.githubusercontent.com/assets/11179944/26012799/bdffc4c6-3723-11e7-9537-955cbd44c4f2.png)
2. Permite guardar rubro sin ningun material y servicio
3.  Permite ingresar número negativo en cantidad de materiales y servicios, cuando das click en guardar no guarda pero desaparecen los caculos y no vuelve a calcular 
![untitled](https://cloud.githubusercontent.com/assets/11179944/26013013/87d0c2c8-3724-11e7-9a24-3672a8c619e9.png)
5. Al darle click en mostrar muestra mal y falta el botón editar
![untitled](https://cloud.githubusercontent.com/assets/11179944/26013193/501877d0-3725-11e7-9885-3e9f431f7073.png)

**Comment by alexjw** [comment]
Y como querés que ponga eso en una linea? el ajax no hice yo y yo no hago esas cosas, y mis queridos compañeros también modificaron el show, el show voy a ver, asignale a otro esta tarea
