### ISSUE TITLE
Generar pdf - presupuesto

### ISSUE THREAD

**Issue by taniamonges** [fatimaTalavera/OnProject#227]
1. Agregar acentos a direcciòn y telèfono
2. Poner correo elèctronico en vez de email
3. Falta el logo de la empresa
4. No muestra el nombre de la obra
5. Mostrar mejor la tabla con la informaciòn
![untitled](https://cloud.githubusercontent.com/assets/11179944/26181509/98400ae2-3b3e-11e7-8fbd-cc2c5152089c.png)

**Comment by EmilioCenturion** [comment]
@taniamonges lo de el logo de la empresa no pude solucionarlo, ya que la imagen se guarda en cloudinary creando un link, y no estoy pudiendo obtener el logo porque da un error diciendo que no existe el link
