### ISSUE TITLE
Facturar al cliente

### ISSUE THREAD

**Issue by taniamonges** [fatimaTalavera/OnProject#253]
- Corregir formato de fecha y agregar acento a condición
![untitled](https://cloud.githubusercontent.com/assets/11179944/26561379/f3181760-448b-11e7-8347-0ba0778a70ce.png)
![untitled](https://cloud.githubusercontent.com/assets/11179944/26561403/2a221616-448c-11e7-9f07-250d61a45169.png)

**Comment by alexjw** [comment]
La fecha no es mi problema, decile al que jodió con el datepicker, o sea Selent
