### ISSUE TITLE
Mejorar CRUD de clientes

### ISSUE THREAD

**Issue by EmilioCenturion** [fatimaTalavera/OnProject#31]
Mejorar vistas de CRUD clientes unificando el estilo con el ABM contratos que servirá de ejemplo

**Comment by taniamonges** [comment]
realizar cambios en el  diseño de la interfaz, correr rails_best_practices en clientes hay errores e el controlador, helper, modelo, vista, resolverlos todos al volver a correr el analizador estatico debe estar en cero errores. Tambien correr brakeman y resolver los errores

**Comment by taniamonges** [comment]
Instalar ruby critic y correrlo

**Comment by taniamonges** [comment]
@ergo-program  solucionar errores al correr los analizadores estaticos

**Comment by taniamonges** [comment]
@ergo-program eliminar apellido de la lista, en vez dde documento que diga ruc, quitar el scroll de la lista 
![untitled](https://cloud.githubusercontent.com/assets/11179944/24085791/fdcdc2dc-0ce0-11e7-8a99-53ef2e43003e.png)

**Comment by taniamonges** [comment]
cambiar show, que diga nombre o razon social, eliminar apellido, que diga ruc en vez de documento
![untitled](https://cloud.githubusercontent.com/assets/11179944/24085815/7853803c-0ce1-11e7-9c8f-6e6929b603a3.png)
