### ISSUE TITLE
Mejorar CRUD de movimientos materiales

### ISSUE THREAD

**Issue by EmilioCenturion** [fatimaTalavera/OnProject#32]
Mejorar vistas de CRUD movimientos materiales unificando el estilo con el ABM contratos que servirá de ejemplo

**Comment by taniamonges** [comment]
@alexjw cambiar el diseño de la interfaz, te podes guiar por crud de clientes, los botones deben estar a la derecha, en vez de decir agregar debe decir guardar, se muestra primero la lista con un boton mas al lado para registrar movimientos.

**Comment by taniamonges** [comment]
@alexjw  tambien correr los analizadores estaticos y resolver todos los errores que tira rails_best_practices y brakeman

**Comment by taniamonges** [comment]
@alexjw  mejorar como se ven las validaciones en movimiento de materiales, que no se hagan pequños los campos
Arreglar errores que salen al correr rails_best_practices
