### ISSUE TITLE
Mejorar CRUD de materiales

### ISSUE THREAD

**Issue by EmilioCenturion** [fatimaTalavera/OnProject#33]
Mejorar vistas de ABM materiales unificando el estilo con el CRUD contratos que servirá de ejemplo

**Comment by taniamonges** [comment]
correr rails_best_practices y corregir todos los errores que tira, hay errores en helper,modelo,vista. Al volver a correr el analizador estatico debe estar en cero errores.

**Comment by taniamonges** [comment]
realizar cambios en el diseño de la interfaz

**Comment by taniamonges** [comment]
@EmilioCenturion  en registrar materiales el boton debe decir guardar

**Comment by taniamonges** [comment]
@EmilioCenturion quitar scroll de la lista
![untitled](https://cloud.githubusercontent.com/assets/11179944/24085927/953fb4d4-0ce3-11e7-91f3-9cf81132a026.png)

**Comment by taniamonges** [comment]
@EmilioCenturion  arreglar vista de registrar materiales, el helper, que aparezca en una sola linea descripcion y unidad de medida
![untitled](https://cloud.githubusercontent.com/assets/11179944/24085941/12071174-0ce4-11e7-84f3-aad28b967954.png)

**Comment by taniamonges** [comment]
@EmilioCenturion  si se pude mejorar el show, esta muy separados juntarlos mas
![untitled](https://cloud.githubusercontent.com/assets/11179944/24085957/afe57bb0-0ce4-11e7-8459-9ee61efbc3dc.png)

**Comment by taniamonges** [comment]
@EmilioCenturion  en editar la misma correcione que en registrar
![untitled](https://cloud.githubusercontent.com/assets/11179944/24085972/faf9fcca-0ce4-11e7-9cf9-18d40e816bce.png)
