### ISSUE TITLE
Realizar los UnitTest para CRUD Usuarios

### ISSUE THREAD

**Issue by EmilioCenturion** [fatimaTalavera/OnProject#34]
Realizar los UnitTest del modelo para CRUD Usuarios. Ver ejemplo enviado por la profesora.

**Comment by taniamonges** [comment]
@rsjavier14  correr tambien los analizadores y resolver errores
![untitled](https://cloud.githubusercontent.com/assets/11179944/24085910/07d71f38-0ce3-11e7-8c1f-77d22e33a2d7.png)
