### ISSUE TITLE
CRUD de Factura Compra

### ISSUE THREAD

**Issue by EmilioCenturion** [fatimaTalavera/OnProject#38]
Guiarse con la documentación de Ingeniería de Software I para saber el comportamiento y los atributos que debe tener.

**Comment by taniamonges** [comment]
@alexjw  en vez de decir movimientos, debe decir detalle de factura, realizar los cambios en la interfaz guiandote por el crud de cliente

**Comment by taniamonges** [comment]
@alexjw  corregir errores al correr rails_best_practices, mejorar como se ven los campos cuando muestra la validacon y mejorar reqistrar factura compra
