### ISSUE TITLE
Validaciones para Clientes.

### ISSUE THREAD

**Issue by ergo-program** [fatimaTalavera/OnProject#44]

**Comment by Jorge199** [comment]
faltan mejorar las validaciones, no me tiene que dejar escribir mas de 50 caracteres en los campos o sea que no me deje ingresar mas caracteres, validar formato para telefono, cuando ingreso un numero invalido en documentos me aparece el mensaje de "no debe estar en blanco" arreglar eso

**Comment by ergo-program** [comment]
Ya están las correcciones, le agregue formato al campo teléfono y en documento no encontré ningún error.

**Comment by Jorge199** [comment]
en el campo telefono tiene que parsear automaticamente los datos ingresados, validaciones de razon social y apellido tienen fallas

**Comment by Jorge199** [comment]
el maxlength de email es muy corto, no puedo ingresar mi correo, maximo tiene que ser 50, limitarme el numero de caracteres ingresados para  ruc

**Comment by Jorge199** [comment]
el maxlength de nombre o razon social es corto pon 100 como minimo, el maxlength de direccion es corto tambien, poner 200 como minimo, pero seria mejor si fuese un text area y al el mensaje de validacion de ruc le falta mostrar como debe ser el formato, o poner una mascara directamente
