### ISSUE TITLE
Validaciones para Materiales

### ISSUE THREAD

**Issue by EmilioCenturion** [fatimaTalavera/OnProject#45]
Utilizando gema client_side_validations

**Comment by taniamonges** [comment]
correr brakeman y corregir errores en las validaciones, debe haber cero errores
tambien correr ruby critic

**Comment by EmilioCenturion** [comment]
Corregidas las vulnerabilidades que se encontraron con los analizadores estáticos en modelo @taniamonges

**Comment by taniamonges** [comment]
@EmilioCenturion  al correr rails_best_practices todavia hay errores en materiales en el helper y vista, corregirlos

**Comment by Jorge199** [comment]
en los campos cantidad, stock mínimo, y precio no me deben dejar ingresar letras u otros caracteres que no sean números, en stock mínimo cuando no ingreso nada me dice que solo se deben ingresar números hay un problema ahí y también hay problemas con la traducción del helper
