### ISSUE TITLE
CRUD Servicios

### ISSUE THREAD

**Issue by EmilioCenturion** [fatimaTalavera/OnProject#54]
Guiarse con la documentación de Ingeniería de Software I para saber el comportamiento y los atributos que debe tener.

**Comment by taniamonges** [comment]
mejorar el show @ergo-program

**Comment by taniamonges** [comment]
@ergo-program  quitar scroll de la lista, arreglar helper
![untitled](https://cloud.githubusercontent.com/assets/11179944/24086011/dfeb3b82-0ce5-11e7-9d64-2c202aef872a.png)

**Comment by taniamonges** [comment]
@ergo-program arreglar 
![untitled](https://cloud.githubusercontent.com/assets/11179944/24086031/2986c464-0ce6-11e7-8467-a1a81bbc8c21.png)

**Comment by taniamonges** [comment]
@ergo-program  tambien aqui 
![untitled](https://cloud.githubusercontent.com/assets/11179944/24086038/6eef21f4-0ce6-11e7-93b6-75b31b5ca501.png)
