### ISSUE TITLE
Validaciones para Proveedores

### ISSUE THREAD

**Issue by EmilioCenturion** [fatimaTalavera/OnProject#65]

**Comment by Jorge199** [comment]
poner el maxlength a los campos, las validaciones de fecha no funcionan y no me dejan agregar el registro
quitar el mensaje de validacion que aparece arriba, con los de abajo ya son suficientes

**Comment by Jorge199** [comment]
el maxlength de nombre o razon social es corto pon 100 como minimo y el mensaje de validacion de ruc le falta mostrar como debe ser el formato, o poner una mascara directamente

**Comment by taniamonges** [comment]
@fatimaTalavera que no me permita ingresar mas de la cantidad de caracteres permitidos en nombre, ruc el mesaje corregir aparatir de 6 numeros me deja guardar.
Que no me permita ingresar numeros en nombre y no me permita ingresar letras en ruc
![untitled](https://cloud.githubusercontent.com/assets/11179944/24561793/21f4e8be-1616-11e7-97ac-6495ec7a6f44.png)

**Comment by taniamonges** [comment]
@fatimaTalavera  que muestre el formato correcto del correo
![untitled](https://cloud.githubusercontent.com/assets/11179944/24561940/e031ac04-1616-11e7-81cf-4803045dbd56.png)

**Comment by Jorge199** [comment]
aun falta mostrar el formato de validacion en el mensaje de validacion de email y direccion tiene que ser un text area con maximo de 200 caracteres

**Comment by Jorge199** [comment]
![proveedores1](https://cloud.githubusercontent.com/assets/21346157/25248326/d26214f4-25db-11e7-8504-29864ce07b2d.png)
nombre o razon social debe ser maximo 100 caracteres
