### ISSUE TITLE
Configuraciones del Sistema

### ISSUE THREAD

**Issue by taniamonges** [fatimaTalavera/OnProject#83]

**Comment by taniamonges** [comment]
@rsjavier14 cambiar nombre a editar configuracion de la empresa
![untitled](https://cloud.githubusercontent.com/assets/11179944/24252351/031ba104-0fbc-11e7-9e7e-f7e6c6185bce.png)

**Comment by taniamonges** [comment]
@rsjavier14  cuando edita el nombre de la empresa creo que deberia cambiar lo que marque en las imagenes tambien.
![untitled](https://cloud.githubusercontent.com/assets/11179944/24252454/456ff014-0fbc-11e7-99eb-6b991744c20f.png)
![untitled](https://cloud.githubusercontent.com/assets/11179944/24252512/6e23b6a8-0fbc-11e7-8e21-09a1e9ed09be.png)

**Comment by taniamonges** [comment]
@rsjavier14  tambien debe haber una opcion para subir el logo de la empresa

**Comment by taniamonges** [comment]
@rsjavier14  resolver
![im2](https://cloud.githubusercontent.com/assets/11179944/24259823/ce3a551a-0fd0-11e7-9887-dc99e64a445d.png)
![ime](https://cloud.githubusercontent.com/assets/11179944/24259833/d67b7a74-0fd0-11e7-8d83-626ee375fd75.png)

**Comment by taniamonges** [comment]
@rsjavier14 donde se muestra la informacion que cargue? Esa informacion puede estar en el inicio

**Comment by rsjavier14** [comment]
informacion que cargue?
