### ISSUE TITLE
Validaciones para Empleados

### ISSUE THREAD

**Issue by Jorge199** [fatimaTalavera/OnProject#86]
el maxlength de direccion es corto pon 150 como maximo, el mensaje de validacion de email le falta mostrar como debe ser el formato y validar correctamente CI con mascaras o normalmente

**Comment by taniamonges** [comment]
@fatimaTalavera corregir validaciones y limites de los campos 
![untitled](https://cloud.githubusercontent.com/assets/11179944/24560492/02cdcb2c-1611-11e7-862a-116d96f7c3d2.png)
![untitled2](https://cloud.githubusercontent.com/assets/11179944/24560498/0606e9ae-1611-11e7-9224-c232066638dc.png)

**Comment by taniamonges** [comment]
@fatimaTalavera  
que no me permita escribir en el campo nombre y apellido numeros, mostrar el formato de correo que es valido un ejemplo
![untitled](https://cloud.githubusercontent.com/assets/11179944/24560872/78365af4-1612-11e7-9b9e-2af7d5396535.png)

**Comment by taniamonges** [comment]
que en el campo ci no me permita escribir  letras ya que solo permite numeros

**Comment by Jorge199** [comment]
![empleados1](https://cloud.githubusercontent.com/assets/21346157/25248633/f21df334-25dc-11e7-8d72-353fe317b06a.png)
maximo 50 caracteres, no puedo completar mi correo
