### ISSUE TITLE
Perfil de Usuario

### ISSUE THREAD

**Issue by taniamonges** [fatimaTalavera/OnProject#88]

**Comment by taniamonges** [comment]
@rsjavier14 en registrar usuario que este alineado hacia la izquierda igual que los demas formularios, y usa form_for que es lo que todos los formularios usan

**Comment by rsjavier14** [comment]
form_for? asi esta 
```ruby
<%= form_for user, validate: true, :html => { class: 'form-horizontal' } do |f| %>
```
