### ISSUE TITLE
Problema en subida de imagenes en configuracion de sistema

### ISSUE THREAD

**Issue by Jorge199** [fatimaTalavera/OnProject#90]
No me deja subir ninguna imagen ni gif porque me tira que el mensaje de que el formato es invalido, nombre hay que ponerle length o algo para que no deje ingresar mas de 27 caracteres funciona la validacion pero es mejor de la otra forma

**Comment by rsjavier14** [comment]
no entiendo porque no les funciona.. si probas aca podras ver que funciona.. actualmente tiene un error si no subis una imagen, eso tengo que solucionar, pero si permite subir jpg png gif y jpeg. Los archivos no deben superar 1mb. https://on-project.herokuapp.com/company_config/1/edit

**Comment by Jorge199** [comment]
localmente probe y no funciona, quizas en heroku funcione, hay que ver que pasa

**Comment by taniamonges** [comment]
@rsjavier14  alinear a la izquierda igual que los demas formularios

**Comment by rsjavier14** [comment]
que hay que alinear a la izquierda?

**Comment by taniamonges** [comment]
@rsjavier14  el texto el margen es muy grande si te fijas en los otros formularios es diferente
![untitled](https://cloud.githubusercontent.com/assets/11179944/24581201/1d630edc-16e5-11e7-978d-07c1c5ba9123.png)
