### ISSUE TITLE
Arreglar movimiento de materiales

### ISSUE THREAD

**Issue by taniamonges** [fatimaTalavera/OnProject#95]
Que funcione correctamente

**Comment by taniamonges** [comment]
@alexjw  los atributos deben estar en ingles, quedamos en que todo debe estar en ingles

**Comment by alexjw** [comment]
Que lo que no funciona?

**Comment by taniamonges** [comment]
Cuando haces click en guardar no guarda

2017-03-29 23:33 GMT-04:00 alexjw <notifications@github.com>:

**Comment by taniamonges** [comment]
@alexjw  quedamos en que se programa en ingles, todo debe estar en ingles, cambiar eso en movimiento de materiales hay palabras en español como restar, cantidad

**Comment by alexjw** [comment]
Claro que sí, después de que haya echo  el abm habíamos quedamos en eso (:

**Comment by taniamonges** [comment]
Si.. y se tenia que cambiar a ingles lo que ya se hicieron 😀
